# Generated by Django 4.1.1 on 2022-10-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_personwordlist_personwordlistword_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonWordListWord',
            new_name='PersonWordListRelation',
        ),
        migrations.AlterField(
            model_name='worddetail',
            name='word_stat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordstat'),
        ),
    ]
