# Generated by Django 4.1.1 on 2022-10-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_rename_personwordlistword_personwordlistrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddetail',
            name='word_stat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_stat', to='dictionary.wordstat'),
        ),
    ]
