# Generated by Django 4.1.1 on 2022-10-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_alter_worddetail_word_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personwordlist',
            name='word',
        ),
        migrations.DeleteModel(
            name='PersonWordListRelation',
        ),
        migrations.AddField(
            model_name='personwordlist',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictionary.word'),
            preserve_default=False,
        ),
    ]
